version: '3.7'

services:
  # definition of tor relay service
  tor-relay:
    # if you want to build yourself
    # build: .
    image: mk0x/docker-tor
    container_name: torRelay
    volumes:
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
    ports:
      - 9001:9001
    networks:
      outpost_tor:

# seperate tor network by creating an own
networks:
  outpost_tor:
    driver: bridge
    name: outpost_tor